.\" Manpage for gotem
.TH GOTEM 1 "December 2024" "1.0.0" "Gotem Manual"
.SH NAME
gotem \- A CLI tool for managing Linux dotfiles
.SH SYNOPSIS
.B gotem
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B gotem
is a CLI tool to organize and track modifications in Linux dotfiles.
.SH OPTIONS
.TP
.B \-h, \-\-help
Display this help message and exit.
.TP
.B \-v, \-\-version
Show the current version of gotem.
.TP
.B \-l, \-\-list
List all tracked dotfiles.
.SH AUTHOR
Written by Quoc Bao.
.SH SEE ALSO
git(1)

