
[stash]
  backup = false
  create = true
  dotpath = "stash"
  keepdot = true
  uselink = false

  [stash.archlinux]
    dotpath = "archlinux"

    [stash.archlinux.exampletxt]
      local_path = "C:\\Users\\ES-01\\dev\\go\\gotem\\example.txt"
      stash_path = "example.txt"

    [stash.archlinux.nvim]
      local_path = "nvim"
      stash_path = "nvim"

    [stash.archlinux.vscode]
      local_path = "C:\\Users\\ES-01\\dev\\go\\gotem\\.vscode"
      stash_path = ".vscode"

  [stash.default]
    backup = true
    dotpath = "default"

    [stash.default.nvim]
      local_path = "~/.config/nvim"
      stash_path = "config/nvim"

    [stash.default.vscode]
      local_path = "C:\\Users\\ES-01\\dev\\go\\gotem\\.vscode"
      stash_path = ".vscode"

    [stash.default.zsh]
      local_path = "~/.zshrc"
      stash_path = "zshrc"

  [stash.new]
    dotpath = "new"

    [stash.new.vscode]
      local_path = "C:\\Users\\ES-01\\dev\\go\\gotem\\.vscode"
      stash_path = ".vscode"

  [stash.ubuntu]
    dotpath = "debian/ubuntu"

    [stash.ubuntu.zsh]
      local_path = "~/.settings/.zsh"
      stash_path = "settings/zsh"
